### ISSUE TITLE
Recurring Integration Scheduler gives Quartz.Core.JobRunShell exception

### ISSUE THREAD

**Issue by Vamps121** [microsoft/Recurring-Integrations-Scheduler#98]
Hello everyone, 

About a year ago we started using Dynamics for our stores. 
The whole idea was to use the MRP to restock the stores automaticly.

Since the start we have never been able to get a reliable MRP export through RIS for our legacy ERP system. 

When we use the original Sales orders composite V2 we get the same error as when we use the custom made sales entity called HSOExportSalesLineEntity.

Every day there is 1 job running for both stores to get the orders in our legacy ERP, but every day we hope both run but in reality one of them goes wrong every now and then and its never the same one. 

Hopefully someone had this error and knows how to fix it. 

I've added the error log that the event viewer throws out, noone seems to know how to fix it because the issue isnt recurring enough to give it a propper analysis.

We use version 2.7.1.0 

Kind regards, 

Robin Kleinhesselink
[30-10 Error log.txt](https://github.com/microsoft/Recurring-Integrations-Scheduler/files/4165442/30-10.Error.log.txt)

**Comment by TomekMelissa** [comment]
Hi Robin,
You are facing issues that should be solved on D365 side. In the log you see that RIS requests fail and D365 responds with "Bad request". Anything else in the log is a "noise" from RIS because I decided to stop the jobs in such cases with thrown exception so the full call stack of RIS can be seen. I think I will change that behaviour because it is giving false impression that the problem lays on RIS side. RIS is only a messenger. Do not blame the messenger :) It is using standard APIs and it is doing so quite well. 
When D365 responds with "Bad request" there is usually more context information in Event log of DMF on D365 servers. Therefore the best way to understand what is going on is to look for clues there. As it is not possible in production instance, the only option is to replicate the same behavior on any sandbox.
I have seen cases where D365 responds with "Bad request" when there are two concurrent requests of import or export at exactly the same time. You mentioned that you run two jobs. Is it possible to schedule those at different times?
I just released v.3.0. I do not really think it can solve your problem, but give it a try.

**Comment by phillipsra16** [comment]
I agree with @TomekMelissa on this one.  We are on version 2.7.1 as well, and after a lot of trial and error we finally determined that most of our "Bad request" issues were caused due to jobs being executed simultaneously.  D365 seems to choke when it receives requests too close together.

To mitigate the issue, we have simply offset executions by a few seconds and always use CRON timers.  If the simple timer is used, then jobs reschedule as of the time the service was started, which runs into collisions more often.  We are also in the process of testing 3.1.0 to see if some of the multi-company functionality helps (almost all of our jobs run in two companies).

**Comment by Vamps121** [comment]
Hello all,

Sorry for the delay in responds just didnt have time to do it :( 

We have been testing with the V3.0 on our acceptance environment but its still throwing it back this time its not endlessly running in the ris but it just stops trying. 

For the other questions, we use the cron timer and they are 15 minutes after eachother so 16:15 and 16:30. 
For some reason since the 10.0.8 update in dynamics it has not failed so maybe the error is fixed on D365 side and its finnaly working!

Thanks for the responses !
